// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="encryfinal_encryfinal,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.826000,HLS_SYN_LAT=1610613182,HLS_SYN_TPT=none,HLS_SYN_MEM=14,HLS_SYN_DSP=0,HLS_SYN_FF=2308,HLS_SYN_LUT=2342,HLS_VERSION=2023_2}" *)

module encryfinal (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 8;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] speechSignal_q0;
reg   [24:0] step_1_reg_179;
wire    ap_CS_fsm_state3;
wire   [23:0] tmp_fu_137_p4;
reg   [23:0] tmp_reg_184;
wire   [24:0] zext_ln46_fu_153_p1;
reg   [24:0] zext_ln46_reg_192;
wire    ap_CS_fsm_state5;
reg   [3:0] trunc_ln_reg_197;
reg   [3:0] temp_address0;
reg    temp_ce0;
reg    temp_we0;
reg   [63:0] temp_d0;
wire   [63:0] temp_q0;
reg   [3:0] transformedSignal_address0;
reg    transformedSignal_ce0;
reg    transformedSignal_we0;
reg   [63:0] transformedSignal_d0;
wire   [63:0] transformedSignal_q0;
reg    transformedSignal_ce1;
wire   [63:0] transformedSignal_q1;
reg   [3:0] multipliedSignal_address0;
reg    multipliedSignal_ce0;
reg    multipliedSignal_we0;
wire   [63:0] multipliedSignal_q0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_ap_start;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_ap_done;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_ap_idle;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_ap_ready;
wire   [3:0] grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_speechSignal_address0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_speechSignal_ce0;
wire   [3:0] grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_transformedSignal_address0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_transformedSignal_ce0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_transformedSignal_we0;
wire   [63:0] grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_transformedSignal_d0;
wire    grp_encryfinal_Pipeline_2_fu_94_ap_start;
wire    grp_encryfinal_Pipeline_2_fu_94_ap_done;
wire    grp_encryfinal_Pipeline_2_fu_94_ap_idle;
wire    grp_encryfinal_Pipeline_2_fu_94_ap_ready;
wire   [3:0] grp_encryfinal_Pipeline_2_fu_94_temp_address0;
wire    grp_encryfinal_Pipeline_2_fu_94_temp_ce0;
wire    grp_encryfinal_Pipeline_2_fu_94_temp_we0;
wire   [63:0] grp_encryfinal_Pipeline_2_fu_94_temp_d0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_ap_start;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_ap_done;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_ap_idle;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_ap_ready;
wire   [3:0] grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_transformedSignal_address0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_transformedSignal_ce0;
wire   [3:0] grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_multipliedSignal_address0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_multipliedSignal_ce0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_multipliedSignal_we0;
wire   [63:0] grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_multipliedSignal_d0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_ap_start;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_ap_done;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_ap_idle;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_ap_ready;
wire   [3:0] grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_transformedSignal_address0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_transformedSignal_ce0;
wire   [3:0] grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_transformedSignal_address1;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_transformedSignal_ce1;
wire   [3:0] grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_temp_address0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_temp_ce0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_temp_we0;
wire   [63:0] grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_temp_d0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_ap_start;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_ap_done;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_ap_idle;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_ap_ready;
wire   [3:0] grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_temp_address0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_temp_ce0;
wire   [3:0] grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_transformedSignal_address0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_transformedSignal_ce0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_transformedSignal_we0;
wire   [63:0] grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_transformedSignal_d0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_start;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_done;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_idle;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_ready;
wire   [3:0] grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_multipliedSignal_address0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_multipliedSignal_ce0;
wire   [3:0] grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_encryptedSignal_address0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_encryptedSignal_ce0;
wire    grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_encryptedSignal_we0;
wire   [63:0] grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_encryptedSignal_d0;
reg    grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_encryfinal_Pipeline_2_fu_94_ap_start_reg;
wire   [0:0] icmp_ln44_fu_147_p2;
wire    ap_CS_fsm_state4;
reg    grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_ap_start_reg;
wire    ap_CS_fsm_state9;
reg    grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg   [24:0] step_fu_70;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_ap_start_reg = 1'b0;
#0 grp_encryfinal_Pipeline_2_fu_94_ap_start_reg = 1'b0;
#0 grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_ap_start_reg = 1'b0;
#0 grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_ap_start_reg = 1'b0;
#0 grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_ap_start_reg = 1'b0;
#0 grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_start_reg = 1'b0;
#0 step_fu_70 = 25'd0;
end

encryfinal_temp_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
temp_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(temp_address0),
    .ce0(temp_ce0),
    .we0(temp_we0),
    .d0(temp_d0),
    .q0(temp_q0)
);

encryfinal_transformedSignal_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
transformedSignal_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(transformedSignal_address0),
    .ce0(transformedSignal_ce0),
    .we0(transformedSignal_we0),
    .d0(transformedSignal_d0),
    .q0(transformedSignal_q0),
    .address1(grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_transformedSignal_address1),
    .ce1(transformedSignal_ce1),
    .q1(transformedSignal_q1)
);

encryfinal_temp_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
multipliedSignal_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(multipliedSignal_address0),
    .ce0(multipliedSignal_ce0),
    .we0(multipliedSignal_we0),
    .d0(grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_multipliedSignal_d0),
    .q0(multipliedSignal_q0)
);

encryfinal_encryfinal_Pipeline_VITIS_LOOP_40_1 grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_ap_start),
    .ap_done(grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_ap_done),
    .ap_idle(grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_ap_idle),
    .ap_ready(grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_ap_ready),
    .speechSignal_address0(grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_speechSignal_address0),
    .speechSignal_ce0(grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_speechSignal_ce0),
    .speechSignal_q0(speechSignal_q0),
    .transformedSignal_address0(grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_transformedSignal_address0),
    .transformedSignal_ce0(grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_transformedSignal_ce0),
    .transformedSignal_we0(grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_transformedSignal_we0),
    .transformedSignal_d0(grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_transformedSignal_d0)
);

encryfinal_encryfinal_Pipeline_2 grp_encryfinal_Pipeline_2_fu_94(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_encryfinal_Pipeline_2_fu_94_ap_start),
    .ap_done(grp_encryfinal_Pipeline_2_fu_94_ap_done),
    .ap_idle(grp_encryfinal_Pipeline_2_fu_94_ap_idle),
    .ap_ready(grp_encryfinal_Pipeline_2_fu_94_ap_ready),
    .temp_address0(grp_encryfinal_Pipeline_2_fu_94_temp_address0),
    .temp_ce0(grp_encryfinal_Pipeline_2_fu_94_temp_ce0),
    .temp_we0(grp_encryfinal_Pipeline_2_fu_94_temp_we0),
    .temp_d0(grp_encryfinal_Pipeline_2_fu_94_temp_d0)
);

encryfinal_encryfinal_Pipeline_VITIS_LOOP_86_1 grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_ap_start),
    .ap_done(grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_ap_done),
    .ap_idle(grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_ap_idle),
    .ap_ready(grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_ap_ready),
    .transformedSignal_address0(grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_transformedSignal_address0),
    .transformedSignal_ce0(grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_transformedSignal_ce0),
    .transformedSignal_q0(transformedSignal_q0),
    .multipliedSignal_address0(grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_multipliedSignal_address0),
    .multipliedSignal_ce0(grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_multipliedSignal_ce0),
    .multipliedSignal_we0(grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_multipliedSignal_we0),
    .multipliedSignal_d0(grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_multipliedSignal_d0)
);

encryfinal_encryfinal_Pipeline_VITIS_LOOP_46_3 grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_ap_start),
    .ap_done(grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_ap_done),
    .ap_idle(grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_ap_idle),
    .ap_ready(grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_ap_ready),
    .step_2(zext_ln46_reg_192),
    .transformedSignal_address0(grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_transformedSignal_address0),
    .transformedSignal_ce0(grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_transformedSignal_ce0),
    .transformedSignal_q0(transformedSignal_q0),
    .transformedSignal_address1(grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_transformedSignal_address1),
    .transformedSignal_ce1(grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_transformedSignal_ce1),
    .transformedSignal_q1(transformedSignal_q1),
    .temp_address0(grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_temp_address0),
    .temp_ce0(grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_temp_ce0),
    .temp_we0(grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_temp_we0),
    .temp_d0(grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_temp_d0),
    .trunc_ln(trunc_ln_reg_197)
);

encryfinal_encryfinal_Pipeline_VITIS_LOOP_50_4 grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_ap_start),
    .ap_done(grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_ap_done),
    .ap_idle(grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_ap_idle),
    .ap_ready(grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_ap_ready),
    .step(step_1_reg_179),
    .temp_address0(grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_temp_address0),
    .temp_ce0(grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_temp_ce0),
    .temp_q0(temp_q0),
    .transformedSignal_address0(grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_transformedSignal_address0),
    .transformedSignal_ce0(grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_transformedSignal_ce0),
    .transformedSignal_we0(grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_transformedSignal_we0),
    .transformedSignal_d0(grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_transformedSignal_d0)
);

encryfinal_encryfinal_Pipeline_VITIS_LOOP_64_1 grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_start),
    .ap_done(grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_done),
    .ap_idle(grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_idle),
    .ap_ready(grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_ready),
    .multipliedSignal_address0(grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_multipliedSignal_address0),
    .multipliedSignal_ce0(grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_multipliedSignal_ce0),
    .multipliedSignal_q0(multipliedSignal_q0),
    .encryptedSignal_address0(grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_encryptedSignal_address0),
    .encryptedSignal_ce0(grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_encryptedSignal_ce0),
    .encryptedSignal_we0(grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_encryptedSignal_we0),
    .encryptedSignal_d0(grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_encryptedSignal_d0)
);

encryfinal_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .speechSignal_address0(grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_speechSignal_address0),
    .speechSignal_ce0(grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_speechSignal_ce0),
    .speechSignal_q0(speechSignal_q0),
    .encryptedSignal_address0(grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_encryptedSignal_address0),
    .encryptedSignal_ce0(grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_encryptedSignal_ce0),
    .encryptedSignal_we0(grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_encryptedSignal_we0),
    .encryptedSignal_d0(grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_encryptedSignal_d0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_encryfinal_Pipeline_2_fu_94_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln44_fu_147_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_encryfinal_Pipeline_2_fu_94_ap_start_reg <= 1'b1;
        end else if ((grp_encryfinal_Pipeline_2_fu_94_ap_ready == 1'b1)) begin
            grp_encryfinal_Pipeline_2_fu_94_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_ap_start_reg <= 1'b1;
        end else if ((grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_ap_ready == 1'b1)) begin
            grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_ap_start_reg <= 1'b1;
        end else if ((grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_ap_ready == 1'b1)) begin
            grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_ap_start_reg <= 1'b1;
        end else if ((grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_ap_ready == 1'b1)) begin
            grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_start_reg <= 1'b1;
        end else if ((grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_ready == 1'b1)) begin
            grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln44_fu_147_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_ap_start_reg <= 1'b1;
        end else if ((grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_ap_ready == 1'b1)) begin
            grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                step_fu_70[0] <= 1'b0;
        step_fu_70[1] <= 1'b0;
        step_fu_70[2] <= 1'b0;
        step_fu_70[3] <= 1'b0;
        step_fu_70[4] <= 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
                step_fu_70[4 : 0] <= zext_ln46_fu_153_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        step_1_reg_179[4 : 0] <= step_fu_70[4 : 0];
        tmp_reg_184 <= {{step_fu_70[24:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        trunc_ln_reg_197 <= {{step_fu_70[4:1]}};
        zext_ln46_reg_192[3 : 0] <= zext_ln46_fu_153_p1[3 : 0];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_encryfinal_Pipeline_2_fu_94_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        multipliedSignal_address0 = grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_multipliedSignal_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        multipliedSignal_address0 = grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_multipliedSignal_address0;
    end else begin
        multipliedSignal_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        multipliedSignal_ce0 = grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_multipliedSignal_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        multipliedSignal_ce0 = grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_multipliedSignal_ce0;
    end else begin
        multipliedSignal_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        multipliedSignal_we0 = grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_multipliedSignal_we0;
    end else begin
        multipliedSignal_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        temp_address0 = grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_temp_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        temp_address0 = grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_temp_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        temp_address0 = grp_encryfinal_Pipeline_2_fu_94_temp_address0;
    end else begin
        temp_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        temp_ce0 = grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_temp_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        temp_ce0 = grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_temp_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        temp_ce0 = grp_encryfinal_Pipeline_2_fu_94_temp_ce0;
    end else begin
        temp_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        temp_d0 = grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_temp_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        temp_d0 = grp_encryfinal_Pipeline_2_fu_94_temp_d0;
    end else begin
        temp_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        temp_we0 = grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_temp_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        temp_we0 = grp_encryfinal_Pipeline_2_fu_94_temp_we0;
    end else begin
        temp_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        transformedSignal_address0 = grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_transformedSignal_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        transformedSignal_address0 = grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_transformedSignal_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        transformedSignal_address0 = grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_transformedSignal_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        transformedSignal_address0 = grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_transformedSignal_address0;
    end else begin
        transformedSignal_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        transformedSignal_ce0 = grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_transformedSignal_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        transformedSignal_ce0 = grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_transformedSignal_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        transformedSignal_ce0 = grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_transformedSignal_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        transformedSignal_ce0 = grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_transformedSignal_ce0;
    end else begin
        transformedSignal_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        transformedSignal_ce1 = grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_transformedSignal_ce1;
    end else begin
        transformedSignal_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        transformedSignal_d0 = grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_transformedSignal_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        transformedSignal_d0 = grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_transformedSignal_d0;
    end else begin
        transformedSignal_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        transformedSignal_we0 = grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_transformedSignal_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        transformedSignal_we0 = grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_transformedSignal_we0;
    end else begin
        transformedSignal_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln44_fu_147_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_encryfinal_Pipeline_2_fu_94_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_encryfinal_Pipeline_2_fu_94_ap_start = grp_encryfinal_Pipeline_2_fu_94_ap_start_reg;

assign grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_ap_start = grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_86_ap_start_reg;

assign grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_ap_start = grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_107_ap_start_reg;

assign grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_ap_start = grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_115_ap_start_reg;

assign grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_start = grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_122_ap_start_reg;

assign grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_ap_start = grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_99_ap_start_reg;

assign icmp_ln44_fu_147_p2 = ((tmp_fu_137_p4 == 24'd0) ? 1'b1 : 1'b0);

assign tmp_fu_137_p4 = {{step_fu_70[24:1]}};

assign zext_ln46_fu_153_p1 = tmp_reg_184;

always @ (posedge ap_clk) begin
    step_1_reg_179[24:5] <= 20'b00000000000000000000;
    zext_ln46_reg_192[24:4] <= 21'b000000000000000000000;
    step_fu_70[24:5] <= 20'b00000000000000000000;
end

endmodule //encryfinal
