#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("dt", 32, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("num_iterations", 32, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("alpha", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("sigma", 32, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("beta", 32, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("gamma", 32, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("epsilon", 32, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("x_out", 32, hls_out, 7, "ap_vld", "out_data", 1),
	Port_Property("x_out_ap_vld", 1, hls_out, 7, "ap_vld", "out_vld", 1),
	Port_Property("y_out", 32, hls_out, 8, "ap_vld", "out_data", 1),
	Port_Property("y_out_ap_vld", 1, hls_out, 8, "ap_vld", "out_vld", 1),
	Port_Property("z_out", 32, hls_out, 9, "ap_vld", "out_data", 1),
	Port_Property("z_out_ap_vld", 1, hls_out, 9, "ap_vld", "out_vld", 1),
	Port_Property("w_out", 32, hls_out, 10, "ap_vld", "out_data", 1),
	Port_Property("w_out_ap_vld", 1, hls_out, 10, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "chensy";
