-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity encryfinal is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    speechSignal_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    speechSignal_ce0 : OUT STD_LOGIC;
    speechSignal_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    encryptedSignal_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    encryptedSignal_ce0 : OUT STD_LOGIC;
    encryptedSignal_we0 : OUT STD_LOGIC;
    encryptedSignal_d0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of encryfinal is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "encryfinal_encryfinal,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.826000,HLS_SYN_LAT=1610613182,HLS_SYN_TPT=none,HLS_SYN_MEM=10,HLS_SYN_DSP=0,HLS_SYN_FF=2112,HLS_SYN_LUT=2154,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv25_10 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000010000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal step_1_reg_167 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_fu_125_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_reg_172 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln46_fu_141_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln46_reg_180 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal trunc_ln_reg_185 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_ce0 : STD_LOGIC;
    signal temp_we0 : STD_LOGIC;
    signal temp_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal temp_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal transformedSignal_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal transformedSignal_ce0 : STD_LOGIC;
    signal transformedSignal_we0 : STD_LOGIC;
    signal transformedSignal_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal transformedSignal_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal transformedSignal_ce1 : STD_LOGIC;
    signal transformedSignal_q1 : STD_LOGIC_VECTOR (63 downto 0);
    signal multipliedSignal_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal multipliedSignal_ce0 : STD_LOGIC;
    signal multipliedSignal_we0 : STD_LOGIC;
    signal multipliedSignal_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_start : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_done : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_idle : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_ready : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_speechSignal_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_speechSignal_ce0 : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_transformedSignal_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_transformedSignal_ce0 : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_transformedSignal_we0 : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_transformedSignal_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_encryfinal_Pipeline_2_fu_82_ap_start : STD_LOGIC;
    signal grp_encryfinal_Pipeline_2_fu_82_ap_done : STD_LOGIC;
    signal grp_encryfinal_Pipeline_2_fu_82_ap_idle : STD_LOGIC;
    signal grp_encryfinal_Pipeline_2_fu_82_ap_ready : STD_LOGIC;
    signal grp_encryfinal_Pipeline_2_fu_82_temp_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_encryfinal_Pipeline_2_fu_82_temp_ce0 : STD_LOGIC;
    signal grp_encryfinal_Pipeline_2_fu_82_temp_we0 : STD_LOGIC;
    signal grp_encryfinal_Pipeline_2_fu_82_temp_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_start : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_done : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_idle : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_ready : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_transformedSignal_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_transformedSignal_ce0 : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_multipliedSignal_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_multipliedSignal_ce0 : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_multipliedSignal_we0 : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_multipliedSignal_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_start : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_done : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_idle : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_ready : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_transformedSignal_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_transformedSignal_ce0 : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_transformedSignal_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_transformedSignal_ce1 : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_temp_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_temp_ce0 : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_temp_we0 : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_temp_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_start : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_done : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_idle : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_ready : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_temp_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_temp_ce0 : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_transformedSignal_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_transformedSignal_ce0 : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_transformedSignal_we0 : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_transformedSignal_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_start : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_done : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_idle : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_ready : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_multipliedSignal_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_multipliedSignal_ce0 : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_encryptedSignal_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_encryptedSignal_ce0 : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_encryptedSignal_we0 : STD_LOGIC;
    signal grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_encryptedSignal_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_encryfinal_Pipeline_2_fu_82_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln44_fu_135_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal step_fu_58 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component encryfinal_encryfinal_Pipeline_VITIS_LOOP_40_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        speechSignal_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        speechSignal_ce0 : OUT STD_LOGIC;
        speechSignal_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        transformedSignal_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        transformedSignal_ce0 : OUT STD_LOGIC;
        transformedSignal_we0 : OUT STD_LOGIC;
        transformedSignal_d0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component encryfinal_encryfinal_Pipeline_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        temp_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        temp_ce0 : OUT STD_LOGIC;
        temp_we0 : OUT STD_LOGIC;
        temp_d0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component encryfinal_encryfinal_Pipeline_VITIS_LOOP_86_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        transformedSignal_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        transformedSignal_ce0 : OUT STD_LOGIC;
        transformedSignal_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        multipliedSignal_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        multipliedSignal_ce0 : OUT STD_LOGIC;
        multipliedSignal_we0 : OUT STD_LOGIC;
        multipliedSignal_d0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component encryfinal_encryfinal_Pipeline_VITIS_LOOP_46_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        step_2 : IN STD_LOGIC_VECTOR (24 downto 0);
        transformedSignal_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        transformedSignal_ce0 : OUT STD_LOGIC;
        transformedSignal_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        transformedSignal_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        transformedSignal_ce1 : OUT STD_LOGIC;
        transformedSignal_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
        temp_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        temp_ce0 : OUT STD_LOGIC;
        temp_we0 : OUT STD_LOGIC;
        temp_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        trunc_ln : IN STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component encryfinal_encryfinal_Pipeline_VITIS_LOOP_50_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        step : IN STD_LOGIC_VECTOR (24 downto 0);
        temp_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        temp_ce0 : OUT STD_LOGIC;
        temp_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        transformedSignal_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        transformedSignal_ce0 : OUT STD_LOGIC;
        transformedSignal_we0 : OUT STD_LOGIC;
        transformedSignal_d0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component encryfinal_encryfinal_Pipeline_VITIS_LOOP_64_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        multipliedSignal_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        multipliedSignal_ce0 : OUT STD_LOGIC;
        multipliedSignal_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        encryptedSignal_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        encryptedSignal_ce0 : OUT STD_LOGIC;
        encryptedSignal_we0 : OUT STD_LOGIC;
        encryptedSignal_d0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component encryfinal_temp_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (63 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component encryfinal_transformedSignal_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (63 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    temp_U : component encryfinal_temp_RAM_AUTO_1R1W
    generic map (
        DataWidth => 64,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => temp_address0,
        ce0 => temp_ce0,
        we0 => temp_we0,
        d0 => temp_d0,
        q0 => temp_q0);

    transformedSignal_U : component encryfinal_transformedSignal_RAM_AUTO_1R1W
    generic map (
        DataWidth => 64,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => transformedSignal_address0,
        ce0 => transformedSignal_ce0,
        we0 => transformedSignal_we0,
        d0 => transformedSignal_d0,
        q0 => transformedSignal_q0,
        address1 => grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_transformedSignal_address1,
        ce1 => transformedSignal_ce1,
        q1 => transformedSignal_q1);

    multipliedSignal_U : component encryfinal_temp_RAM_AUTO_1R1W
    generic map (
        DataWidth => 64,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => multipliedSignal_address0,
        ce0 => multipliedSignal_ce0,
        we0 => multipliedSignal_we0,
        d0 => grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_multipliedSignal_d0,
        q0 => multipliedSignal_q0);

    grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74 : component encryfinal_encryfinal_Pipeline_VITIS_LOOP_40_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_start,
        ap_done => grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_done,
        ap_idle => grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_idle,
        ap_ready => grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_ready,
        speechSignal_address0 => grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_speechSignal_address0,
        speechSignal_ce0 => grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_speechSignal_ce0,
        speechSignal_q0 => speechSignal_q0,
        transformedSignal_address0 => grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_transformedSignal_address0,
        transformedSignal_ce0 => grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_transformedSignal_ce0,
        transformedSignal_we0 => grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_transformedSignal_we0,
        transformedSignal_d0 => grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_transformedSignal_d0);

    grp_encryfinal_Pipeline_2_fu_82 : component encryfinal_encryfinal_Pipeline_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_encryfinal_Pipeline_2_fu_82_ap_start,
        ap_done => grp_encryfinal_Pipeline_2_fu_82_ap_done,
        ap_idle => grp_encryfinal_Pipeline_2_fu_82_ap_idle,
        ap_ready => grp_encryfinal_Pipeline_2_fu_82_ap_ready,
        temp_address0 => grp_encryfinal_Pipeline_2_fu_82_temp_address0,
        temp_ce0 => grp_encryfinal_Pipeline_2_fu_82_temp_ce0,
        temp_we0 => grp_encryfinal_Pipeline_2_fu_82_temp_we0,
        temp_d0 => grp_encryfinal_Pipeline_2_fu_82_temp_d0);

    grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87 : component encryfinal_encryfinal_Pipeline_VITIS_LOOP_86_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_start,
        ap_done => grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_done,
        ap_idle => grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_idle,
        ap_ready => grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_ready,
        transformedSignal_address0 => grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_transformedSignal_address0,
        transformedSignal_ce0 => grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_transformedSignal_ce0,
        transformedSignal_q0 => transformedSignal_q0,
        multipliedSignal_address0 => grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_multipliedSignal_address0,
        multipliedSignal_ce0 => grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_multipliedSignal_ce0,
        multipliedSignal_we0 => grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_multipliedSignal_we0,
        multipliedSignal_d0 => grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_multipliedSignal_d0);

    grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95 : component encryfinal_encryfinal_Pipeline_VITIS_LOOP_46_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_start,
        ap_done => grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_done,
        ap_idle => grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_idle,
        ap_ready => grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_ready,
        step_2 => zext_ln46_reg_180,
        transformedSignal_address0 => grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_transformedSignal_address0,
        transformedSignal_ce0 => grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_transformedSignal_ce0,
        transformedSignal_q0 => transformedSignal_q0,
        transformedSignal_address1 => grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_transformedSignal_address1,
        transformedSignal_ce1 => grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_transformedSignal_ce1,
        transformedSignal_q1 => transformedSignal_q1,
        temp_address0 => grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_temp_address0,
        temp_ce0 => grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_temp_ce0,
        temp_we0 => grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_temp_we0,
        temp_d0 => grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_temp_d0,
        trunc_ln => trunc_ln_reg_185);

    grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103 : component encryfinal_encryfinal_Pipeline_VITIS_LOOP_50_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_start,
        ap_done => grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_done,
        ap_idle => grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_idle,
        ap_ready => grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_ready,
        step => step_1_reg_167,
        temp_address0 => grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_temp_address0,
        temp_ce0 => grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_temp_ce0,
        temp_q0 => temp_q0,
        transformedSignal_address0 => grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_transformedSignal_address0,
        transformedSignal_ce0 => grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_transformedSignal_ce0,
        transformedSignal_we0 => grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_transformedSignal_we0,
        transformedSignal_d0 => grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_transformedSignal_d0);

    grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110 : component encryfinal_encryfinal_Pipeline_VITIS_LOOP_64_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_start,
        ap_done => grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_done,
        ap_idle => grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_idle,
        ap_ready => grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_ready,
        multipliedSignal_address0 => grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_multipliedSignal_address0,
        multipliedSignal_ce0 => grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_multipliedSignal_ce0,
        multipliedSignal_q0 => multipliedSignal_q0,
        encryptedSignal_address0 => grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_encryptedSignal_address0,
        encryptedSignal_ce0 => grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_encryptedSignal_ce0,
        encryptedSignal_we0 => grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_encryptedSignal_we0,
        encryptedSignal_d0 => grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_encryptedSignal_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_encryfinal_Pipeline_2_fu_82_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_encryfinal_Pipeline_2_fu_82_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln44_fu_135_p2 = ap_const_lv1_0))) then 
                    grp_encryfinal_Pipeline_2_fu_82_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_encryfinal_Pipeline_2_fu_82_ap_ready = ap_const_logic_1)) then 
                    grp_encryfinal_Pipeline_2_fu_82_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_ready = ap_const_logic_1)) then 
                    grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_ready = ap_const_logic_1)) then 
                    grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_ready = ap_const_logic_1)) then 
                    grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                    grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_ready = ap_const_logic_1)) then 
                    grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln44_fu_135_p2 = ap_const_lv1_1))) then 
                    grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_ready = ap_const_logic_1)) then 
                    grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    step_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                step_fu_58(0) <= '0';
                step_fu_58(1) <= '0';
                step_fu_58(2) <= '0';
                step_fu_58(3) <= '0';
                step_fu_58(4) <= '1';
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                                step_fu_58(4 downto 0) <= zext_ln46_fu_141_p1(4 downto 0);
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                    step_1_reg_167(4 downto 0) <= step_fu_58(4 downto 0);
                tmp_reg_172 <= step_fu_58(24 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                trunc_ln_reg_185 <= step_fu_58(4 downto 1);
                    zext_ln46_reg_180(3 downto 0) <= zext_ln46_fu_141_p1(3 downto 0);
            end if;
        end if;
    end process;
    step_1_reg_167(24 downto 5) <= "00000000000000000000";
    zext_ln46_reg_180(24 downto 4) <= "000000000000000000000";
    step_fu_58(24 downto 5) <= "00000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_done, grp_encryfinal_Pipeline_2_fu_82_ap_done, grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_done, grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_done, grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_done, grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_done, ap_CS_fsm_state2, icmp_ln44_fu_135_p2, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state6, ap_CS_fsm_state8, ap_CS_fsm_state11)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln44_fu_135_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_encryfinal_Pipeline_2_fu_82_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state11) and (grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state11_blk_assign_proc : process(grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_done)
    begin
        if ((grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_done)
    begin
        if ((grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_encryfinal_Pipeline_2_fu_82_ap_done)
    begin
        if ((grp_encryfinal_Pipeline_2_fu_82_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_done)
    begin
        if ((grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_done)
    begin
        if ((grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_done)
    begin
        if ((grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_done, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) and (grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_done, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) and (grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    encryptedSignal_address0 <= grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_encryptedSignal_address0;
    encryptedSignal_ce0 <= grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_encryptedSignal_ce0;
    encryptedSignal_d0 <= grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_encryptedSignal_d0;
    encryptedSignal_we0 <= grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_encryptedSignal_we0;
    grp_encryfinal_Pipeline_2_fu_82_ap_start <= grp_encryfinal_Pipeline_2_fu_82_ap_start_reg;
    grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_start <= grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_ap_start_reg;
    grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_start <= grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_ap_start_reg;
    grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_start <= grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_ap_start_reg;
    grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_start <= grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_ap_start_reg;
    grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_start <= grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_ap_start_reg;
    icmp_ln44_fu_135_p2 <= "1" when (tmp_fu_125_p4 = ap_const_lv24_0) else "0";

    multipliedSignal_address0_assign_proc : process(grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_multipliedSignal_address0, grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_multipliedSignal_address0, ap_CS_fsm_state9, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            multipliedSignal_address0 <= grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_multipliedSignal_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            multipliedSignal_address0 <= grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_multipliedSignal_address0;
        else 
            multipliedSignal_address0 <= "XXXX";
        end if; 
    end process;


    multipliedSignal_ce0_assign_proc : process(grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_multipliedSignal_ce0, grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_multipliedSignal_ce0, ap_CS_fsm_state9, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            multipliedSignal_ce0 <= grp_encryfinal_Pipeline_VITIS_LOOP_64_1_fu_110_multipliedSignal_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            multipliedSignal_ce0 <= grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_multipliedSignal_ce0;
        else 
            multipliedSignal_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    multipliedSignal_we0_assign_proc : process(grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_multipliedSignal_we0, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            multipliedSignal_we0 <= grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_multipliedSignal_we0;
        else 
            multipliedSignal_we0 <= ap_const_logic_0;
        end if; 
    end process;

    speechSignal_address0 <= grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_speechSignal_address0;
    speechSignal_ce0 <= grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_speechSignal_ce0;

    temp_address0_assign_proc : process(grp_encryfinal_Pipeline_2_fu_82_temp_address0, grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_temp_address0, grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_temp_address0, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            temp_address0 <= grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_temp_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            temp_address0 <= grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_temp_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            temp_address0 <= grp_encryfinal_Pipeline_2_fu_82_temp_address0;
        else 
            temp_address0 <= "XXXX";
        end if; 
    end process;


    temp_ce0_assign_proc : process(grp_encryfinal_Pipeline_2_fu_82_temp_ce0, grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_temp_ce0, grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_temp_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            temp_ce0 <= grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_temp_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            temp_ce0 <= grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_temp_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            temp_ce0 <= grp_encryfinal_Pipeline_2_fu_82_temp_ce0;
        else 
            temp_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    temp_d0_assign_proc : process(grp_encryfinal_Pipeline_2_fu_82_temp_d0, grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_temp_d0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            temp_d0 <= grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_temp_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            temp_d0 <= grp_encryfinal_Pipeline_2_fu_82_temp_d0;
        else 
            temp_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    temp_we0_assign_proc : process(grp_encryfinal_Pipeline_2_fu_82_temp_we0, grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_temp_we0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            temp_we0 <= grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_temp_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            temp_we0 <= grp_encryfinal_Pipeline_2_fu_82_temp_we0;
        else 
            temp_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_125_p4 <= step_fu_58(24 downto 1);

    transformedSignal_address0_assign_proc : process(grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_transformedSignal_address0, grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_transformedSignal_address0, grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_transformedSignal_address0, grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_transformedSignal_address0, ap_CS_fsm_state2, ap_CS_fsm_state9, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            transformedSignal_address0 <= grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_transformedSignal_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            transformedSignal_address0 <= grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_transformedSignal_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            transformedSignal_address0 <= grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_transformedSignal_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            transformedSignal_address0 <= grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_transformedSignal_address0;
        else 
            transformedSignal_address0 <= "XXXX";
        end if; 
    end process;


    transformedSignal_ce0_assign_proc : process(grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_transformedSignal_ce0, grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_transformedSignal_ce0, grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_transformedSignal_ce0, grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_transformedSignal_ce0, ap_CS_fsm_state2, ap_CS_fsm_state9, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            transformedSignal_ce0 <= grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_transformedSignal_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            transformedSignal_ce0 <= grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_transformedSignal_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            transformedSignal_ce0 <= grp_encryfinal_Pipeline_VITIS_LOOP_86_1_fu_87_transformedSignal_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            transformedSignal_ce0 <= grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_transformedSignal_ce0;
        else 
            transformedSignal_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    transformedSignal_ce1_assign_proc : process(grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_transformedSignal_ce1, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            transformedSignal_ce1 <= grp_encryfinal_Pipeline_VITIS_LOOP_46_3_fu_95_transformedSignal_ce1;
        else 
            transformedSignal_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    transformedSignal_d0_assign_proc : process(grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_transformedSignal_d0, grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_transformedSignal_d0, ap_CS_fsm_state2, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            transformedSignal_d0 <= grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_transformedSignal_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            transformedSignal_d0 <= grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_transformedSignal_d0;
        else 
            transformedSignal_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    transformedSignal_we0_assign_proc : process(grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_transformedSignal_we0, grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_transformedSignal_we0, ap_CS_fsm_state2, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            transformedSignal_we0 <= grp_encryfinal_Pipeline_VITIS_LOOP_50_4_fu_103_transformedSignal_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            transformedSignal_we0 <= grp_encryfinal_Pipeline_VITIS_LOOP_40_1_fu_74_transformedSignal_we0;
        else 
            transformedSignal_we0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln46_fu_141_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_172),25));
end behav;
